basePath: /api/v1
definitions:
  model.Pipeline:
    properties:
      name:
        type: string
    type: object
  util.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: wbx3-pegasus@cisco.com
    name: API Support
    url: https://confluence-eng-gpk2.cisco.com/conf/display/WxCNP/WebexKubed+Pegasus
  description: This is a core API server for CD3.0.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://confluence-eng-gpk2.cisco.com/conf/display/WxCNP/WebexKubed+Pegasus
  title: CD 3.0 Core API
  version: "1.0"
paths:
  /pipelines:
    get:
      consumes:
      - application/json
      description: get pipelines
      parameters:
      - description: name search by q
        format: email
        in: query
        name: q
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Pipeline'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/util.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.HTTPError'
      summary: List pipelines
      tags:
      - pipelines
swagger: "2.0"
